DELIMITER $$
CREATE PROCEDURE ACTIVATE_ALL (IN ADMIN_ID_ INT)
BEGIN
UPDATE ROOM
SET ROOM_STATUS = 0
WHERE
ROOM_ID_ IN (SELECT ROOM_ID
FROM ROOM
JOIN HOTEL_ADMINS ON ROOM.HOTEL_ID = HOTEL_ADMINS.HOTEL_ID
WHERE HOTEL_ADMINS.ADMIN_ID = ADMIN_ID);
END $$
DELIMITER ;