drop procedure if exists CANCEL_ROOM;
DELIMITER $$
CREATE PROCEDURE CANCEL_ROOM(
IN FROM_DATE_ DATE,
IN TO_DATE_ DATE,
IN GUEST_ID_ INT,
IN ROOM_ID_ VARCHAR(255)
)
BEGIN
UPDATE BOOKING
SET BOOKING_STATUS = 0
WHERE GUEST_ID = GUEST_ID_
AND BOOKING_FROM_DATE = FROM_DATE_
AND BOOKING_TO_DATE = TO_DATE_
AND ROOM_ID = ROOM_ID_;
END $$
DELIMITER ;
