DELIMITER $$
CREATE PROCEDURE CANCEL_RESERVATION(
IN FROM_DATE_ DATE,
IN TO_DATE_ DATE,
IN GUEST_ID_ INT,
IN HOTEL_ID_ INT
)
BEGIN
UPDATE BOOKING
SET BOOKING_STATUS = 0
WHERE GUEST_ID = GUEST_ID_
AND BOOKING_FROM_DATE = FROM_DATE_
AND BOOKING_TO_DATE = TO_DATE_
AND ROOM_ID IN (SELECT ROOM_ID FROM ROOM WHERE HOTEL_ID = HOTEL_ID_);
END $$
DELIMITER ;
