DELIMITER $$
CREATE PROCEDURE CONFIRM_PAYMENT(
        		IN PAYMENT_DATE_ DATE,
		IN PAYMENT_CARD_NUMBER_ BIGINT,
		IN VALID_CARD VARCHAR(10)
)
BEGIN
DECLARE PAYMENT_ID_ INT DEFAULT 0;
SELECT PAYMENT_ID INTO PAYMENT_ID_ FROM PAYMENT
WHERE PAYMENT_DATE = PAYMENT_DATE_
AND PAYMENT_CARD = PAYMENT_CARD_NUMBER_;
If VALID_CARD = "VALID"
THEN
	UPDATE PAYMENT SET PAYMENT_STATUS_ID = 2222
	WHERE PAYMENT_ID = PAYMENT_ID_;
ELSE 
	UPDATE PAYMENT SET PAYMENT_STATUS_ID = 5555
	WHERE PAYMENT_ID = PAYMENT_ID_;
END IF;
SELECT * FROM PAYMENT WHERE PAYMENT_ID = PAYMENT_ID_;
END $$
DELIMITER ;