DROP PROCEDURE IF EXISTS SEE_ROOMS;
DELIMITER $$
CREATE PROCEDURE SEE_ROOMS(
IN ADMIN_ID_ INT
)
BEGIN
SELECT * 
FROM room
WHERE ROOM_ID IN (SELECT ROOM_ID FROM ROOM JOIN hotel ON ROOM.HOTEL_ID = HOTEL.HOTEL_ID
JOIN HOTEL_ADMINS ON HOTEL.HOTEL_ID = HOTEL_ADMINS.HOTEL_ID
WHERE HOTEL_ADMINS.ADMIN_ID = ADMIN_ID_);
END $$
DELIMITER ;