DELIMITER $$
CREATE PROCEDURE SEE_VALID(
IN FROM_DATE_ DATE,
IN TO_DATE_ DATE,
IN HOTEL_ID_ int
)
BEGIN
CALL VALID_ROOMS(FROM_DATE_, TO_DATE_, HOTEL_ID_);
SELECT * FROM VALID;
DROP TABLE VALID;
END $$
DELIMITER ;