DELIMITER $$
CREATE PROCEDURE VALID_ROOMS(
IN FROM_DATE_ DATE,
IN TO_DATE_ DATE,
IN HOTEL_ID_ int
)
BEGIN
-- Finds invalid rooms
CREATE TABLE IF NOT EXISTS INVALID
SELECT ROOM.ROOM_ID AS "I_ROOMS"
FROM ROOM
LEFT JOIN BOOKING ON BOOKING.ROOM_ID = ROOM.ROOM_ID
WHERE ROOM.HOTEL_ID = HOTEL_ID_
AND (
(BOOKING_FROM_DATE <= FROM_DATE_ AND FROM_DATE_ < BOOKING_TO_DATE)
 OR 
 (BOOKING_FROM_DATE < TO_DATE_ AND TO_DATE_ <= BOOKING_TO_DATE) 
 OR 
 (FROM_DATE_ < BOOKING_FROM_DATE AND BOOKING_TO_DATE < TO_DATE_) 
 OR 
 (BOOKING_FROM_DATE = FROM_DATE_ AND BOOKING_TO_DATE = TO_DATE_)
 );
-- Uses invalid rooms to find valid rooms
DROP TABLE IF EXISTS VALID;
CREATE TABLE IF NOT EXISTS VALID
SELECT * FROM ROOM
WHERE ROOM.HOTEL_ID = HOTEL_ID_
AND ROOM.ROOM_ID NOT IN (SELECT I_ROOMS FROM INVALID);

DROP TABLE INVALID;
END $$
DELIMITER ;